name: Build üõ†Ô∏è & Publish üöÄ

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'build/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - 'tests/**'
  release:
    types:
      - published
  workflow_dispatch:

env:
  # Disable the .NET logo in the console output.
  DOTNET_NOLOGO: true
  # Disable the .NET first time experience to skip caching NuGet packages and speed up the build.
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending .NET CLI telemetry to Microsoft.
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  # Disable sending NUKE telemetry.
  NUKE_TELEMETRY_OPTOUT: true
  # Set the build number in MinVer.
  MINVERBUILDMETADATA: build.${{github.run_number}}
  # Build Configuration
  CONFIGURATION: Release
  # Packages Directory
  PACKAGES_DIR: ./artifacts/packages-results
  # Set the NuGet packages restore cache directory.
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
  # Disable the Husky pre-commit hooks.
  HUSKY: 0

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v6
        with:
          lfs: false
          fetch-depth: 0

      - name: "Setup .NET SDK"
        uses: actions/setup-dotnet@v5.0.1
        with:
          global-json-file: "./global.json"

      - name: "Setup nuget cache"
        uses: actions/cache@v4
        with:
          path: ${{ env.NUGET_PACKAGES }}
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.Packages.props') }}-${{ hashFiles('**/*.Build.targets') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: "Remove Existing Nuget Source"
        run: dotnet nuget remove source github.com
        shell: pwsh

      - name: "Add Nuget Source"
        run: dotnet nuget add source https://nuget.pkg.github.com/xshaheen/index.json --name github.com --username xshaheen --password ${{ secrets.NUGET_API_KEY }} --store-password-in-clear-text
        shell: pwsh

      - name: ".NET Nuke Build"
        run: ./build.ps1 Compile -Configuration ${{ env.CONFIGURATION }}
        shell: pwsh

      - name: ".NET Nuke Pack"
        run: ./build.ps1 Pack -Configuration ${{ env.CONFIGURATION }}
        shell: pwsh

      - name: "Publish Artifacts"
        uses: actions/upload-artifact@v6
        with:
          name: packages-results
          path: ${{ env.PACKAGES_DIR }}

  push-github-packages:
    name: "Push GitHub Packages"
    needs: build
    runs-on: windows-latest
    if: github.ref == 'refs/heads/main' || github.event_name == 'release'

    permissions:
      packages: write

    environment:
      name: "GitHub Packages"
      url: https://github.com/xshaheen/cs-framework/packages

    steps:
      - name: "Download Artifacts"
        uses: actions/download-artifact@v6
        with:
          name: packages-results

      - name: ".NET NuGet Add Source"
        run: dotnet nuget add source https://nuget.pkg.github.com/xshaheen/index.json --name github.com --username xshaheen --password ${{ secrets.NUGET_API_KEY }} --store-password-in-clear-text
        shell: pwsh

      - name: ".NET NuGet Push"
        run: dotnet nuget push .\*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source github.com --skip-duplicate
        shell: pwsh

      - name: ".NET Symbols Push"
        run: dotnet nuget push .\*.snupkg --api-key ${{ secrets.NUGET_API_KEY }} --source github.com --skip-duplicate
        shell: pwsh
